$filepath = 'C:\Windows\System32\drivers\etc\avmemory.log'
if (Test-Path -Path $filepath) {Remove-Item $filepath}
$Memory1 = (systeminfo | Select-String 'Total Physical Memory:').ToString().Split(':')[1].Trim()
$Memory2 = $Memory1.Replace('MB','')
$Memory3 = $Memory2.Replace(',','')
$TotalMemory = [int]$Memory3
$TotalMemory | Out-File -FilePath $filepath
# SIG # Begin signature block
# MIIFbQYJKoZIhvcNAQcCoIIFXjCCBVoCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU/SXK6P26ujOHzeTlTJazTJfz
# EeagggMPMIIDCzCCAfOgAwIBAgIQG6mH2TUuPLdDloHBUA4KozANBgkqhkiG9w0B
# AQsFADATMREwDwYDVQQDDAhEaWdDZXJ0MjAeFw0xOTA5MTkwMTA2NTBaFw0yMDA5
# MTkwMTI2NTBaMBMxETAPBgNVBAMMCERpZ0NlcnQyMIIBIjANBgkqhkiG9w0BAQEF
# AAOCAQ8AMIIBCgKCAQEAvIKqgtFC9wfCqjaFdd/aoiQngjfPnVkX8BdyCgR7SA7X
# 3ufxOT+GgbPVRj02qeQSs6hAlgXAHe2mlpZb0NL6idOqMwFkZjyTSfA6+GWp3u7M
# 0mwtYG60m6lfkmW4OPEaUXpWxcNQl9b3Puji100JdZdVeYeNivJTyI8jEUawzXmZ
# 5j7AWUGO0yCVu9755eIaVwzutZj+bW+fQbuZLG5rRXue4B6BesOxFJLZIPtKT2EW
# BxWoVmop8JtTNxEzZ8xoU2HxY6b3ASYnDlsdOm7EJmthit2avXi5Logghsm/HFXQ
# u8ujanGvb9fjFtwIQrzkfdXh4biAhWKb2VNy0UxIZQIDAQABo1swWTAOBgNVHQ8B
# Af8EBAMCB4AwEwYDVR0RBAwwCoIIRGlnQ2VydDIwEwYDVR0lBAwwCgYIKwYBBQUH
# AwMwHQYDVR0OBBYEFMvP+FtzP+6kY0NeVeLEdEvwn069MA0GCSqGSIb3DQEBCwUA
# A4IBAQB98Jcei9qTSklMQzZaeQvyoGNCKi0b1tyjafGnGJKrnpq4X9cqH5crio14
# fZF5rZ3LK1648T8wiE5gpf4NwFxUcHXvzKttnNgXBwJsPqhzD/WvxifZySKsozYC
# eNEljO8TZ3NHAg1+J8N+YbI1GnPo17b2AnDK946hAbAx4ihWEoRDRH7Op+Ba2AKl
# 6yrPLMX89hAFHdGJIsGxe7caniLaGwB2XGz/kOTEfz5F3amyXbbg47g1DNFAiSWy
# MASsozuV3misZwgKzSnXGJgceYO7FN7IXv7RNCrFiyifAw39fmP7vXzRhwLU3Y4Q
# hqRSMv24FW4Obtxgnvu1D4m/a/z7MYIByDCCAcQCAQEwJzATMREwDwYDVQQDDAhE
# aWdDZXJ0MgIQG6mH2TUuPLdDloHBUA4KozAJBgUrDgMCGgUAoHgwGAYKKwYBBAGC
# NwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgor
# BgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUFiPFt46z
# ZXvEQQhQe1Gw+CETsBcwDQYJKoZIhvcNAQEBBQAEggEANlMbfZ9vHk2+2XrRvbC0
# DrW4NV4wm47iE8bB5+CZrEmGaBt5DtZvR89WSWXDz1wcCbspPrRa8iSn1gF/UcOy
# sC+oJo9OeWa2Ejhh+kPnwhgBJShy+p9Ylr1FBSeRdbrW0oBUeIvTRWlmBilFaKQS
# N6FuEoCNAsyK1HPAtkISBQMELPmkWKU4I0AAQ6Yx53qVtmLTvd8g58RH6+Ur77Zh
# 6nBojRWEBlYEdZcgL1G9uWjJDTdjJglzEgtTRWzFN4GpL4eNx2rxhKhCzWqil3pN
# X/YgVeFWcRJ6uH+cjoqP5qJcVm+uQMSiNJPDPZqieGZi5ed7LjF7DKzJ5ujH2MBt
# nA==
# SIG # End signature block
